package by.koshman.pharmacy.logic;

public enum CommandName {
	GET_CUSTOMER_COMMAND, ADD_CUSTOMER_COMMAND, ADD_VISIT_COMMAND, UPDATE_VISIT_COMMAND,
	DELETE_VISIT_COMMAND, GET_VISIT_LIST_COMMAND, NO_SUCH_COMMAND 
}
